# Generated by Django 4.2.7 on 2026-08-07 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the room.', primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, help_text='Room number (e.g., 101, 202).', max_length=10, unique=True)),
                ('floor', models.PositiveSmallIntegerField(help_text='Floor number where the room is located.')),
                ('room_type', models.CharField(db_index=True, help_text='Type of room (e.g., Standard, Deluxe, Suite).', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=2, help_text='Maximum number of guests.')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night in USD.', max_digits=10)),
                ('status', models.CharField(choices=[('available', "Bo'sh"), ('booked', 'Band qilingan'), ('occupied', 'Band (mehmon joylashgan)'), ('cleaning', 'Tozalashda'), ('maintenance', "Ta'mirlanmoqda"), ('out_of_service', 'Foydalanishdan chiqarilgan')], db_index=True, default='available', help_text='Current status of the room.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the room.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag. Inactive rooms are hidden from public.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the room was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the room was last updated.')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['number'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='core_room_status_028084_idx'), models.Index(fields=['room_type', 'price_per_night'], name='core_room_room_ty_e93c02_idx')],
            },
        ),
    ]
