# Generated by Django 4.2.7 on 2026-08-10 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the customer.', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Customer's full legal name.", max_length=255)),
                ('passport', models.CharField(db_index=True, help_text='Passport or ID number (e.g., UZ1234567).', max_length=20, unique=True)),
                ('phone', models.CharField(db_index=True, help_text='Phone number in international format (e.g., +998901234567).', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional but unique).', max_length=255, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], help_text='Gender identity.', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth (YYYY-MM-DD). Must not be in the future.', null=True)),
                ('nationality', models.CharField(blank=True, db_index=True, help_text='Nationality (e.g., Uzbekistan, USA).', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Residential address.')),
                ('emergency_contact', models.JSONField(blank=True, default=dict, help_text='Emergency contact: {"name": "John", "phone": "+998...", "relation": "Spouse"}')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='active', help_text='Business status of the customer.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive customers are hidden from active views.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the customer was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the customer was last updated.')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='cust_status_active_idx'), models.Index(fields=['nationality'], name='cust_nationality_idx'), models.Index(fields=['created_at'], name='cust_created_at_idx')],
            },
        ),
    ]
