# Generated by Django 4.2.7 on 2026-08-12 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the payment.', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UZS', 'UZS')], default='USD', help_text='Currency of the payment.', max_length=3)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online')], help_text='Payment method.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Payment status.', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction reference (optional).', max_length=100, null=True, unique=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of payment.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment was last updated.')),
                ('booking', models.ForeignKey(help_text='Associated booking.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['booking', 'status'], name='pay_booking_status_idx'), models.Index(fields=['status'], name='pay_status_idx'), models.Index(fields=['payment_date'], name='pay_payment_date_idx')],
            },
        ),
    ]