# Generated by Django 4.2.7 on 2026-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Public booking reference code (e.g. HMS-2026-ABC123). Only set for public bookings.', max_length=20, null=True, unique=True),
        ),
    ]
