# Generated by Django 4.2.7 on 2026-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximum number of guests (1-5).'),
        ),
    ]
